import Foundation
import NasaNetworkInterface
import PromiseKit

typealias PictureDetailDataProviderProtocol = FavoriteDetailDataProviderProtocol
typealias PictureDetailDataProvider = FavoriteDetailDataProvider
